/*
 * brake_temp.c
 *
 *  Created on: Apr 28, 2026
 *      Author: EvanJ
 */
#include "brake_temp.h"
#include "math.h"
#include "stdio.h"
#include "adc.h"
#include "usart.h"
#include "rtc.h"
#include "cmsis_os.h"
#include "stdio.h"
#include "string.h"
#include "logger.h"
#include "can.h"


// External SPI handle (generated by CubeMX)
extern SPI_HandleTypeDef hspi3;

#define NUM_BRAKE_TEMP_SENSORS 4
double brakeTemps[NUM_BRAKE_TEMP_SENSORS];
#define BRAKETEMP_DELAY_MS 5

double readThermocouples(GPIO_TypeDef* port, uint16_t pin){
    uint8_t brakeTempReceiveBuffer[4] = {0};
    uint8_t dummyTransmit[4] = {0xFF, 0xFF, 0xFF, 0xFF};
    //Write to CS we want.
    HAL_GPIO_WritePin(port, pin, GPIO_PIN_RESET);
    HAL_SPI_TransmitReceive(&hspi3, dummyTransmit,brakeTempReceiveBuffer, 4, HAL_MAX_DELAY);
    HAL_GPIO_WritePin(port, pin, GPIO_PIN_SET);

    uint32_t brakeTemp32Bit = (brakeTempReceiveBuffer[0] << 24) | (brakeTempReceiveBuffer[1] << 16) | (brakeTempReceiveBuffer[2] << 8) | brakeTempReceiveBuffer[3];

    uint32_t raw = brakeTemp32Bit;

    // Fault check
    if (raw & 0x7) {
        //Getting error on one of the thermocouples
    }
    int16_t temp = (raw >> 18) & 0x3FFF;
        if (temp & 0x2000) temp -= 0x4000; // temp |= 0xC000 BIT MASKING

    return temp*0.25; //* 0.25f; //Max31855 is 0.25°C per bit and only 14 bits not 32
}
void StartReadBrakeTempTask(void *argument){
	for(;;){
	    static char concatenatedDistanceMessages[256]; // TODO: make sure we don't concatenate past msg size, look at strncat()
	    char* time;
	    static char* buffer_pos = concatenatedDistanceMessages;;

		brakeTemps[0] = readThermocouples(GPIOD,GPIO_PIN_8);//Brake Temp 1
		brakeTemps[1] = readThermocouples(GPIOD,GPIO_PIN_9);//Brake Temp 2
		brakeTemps[2] = readThermocouples(GPIOD,GPIO_PIN_10);//Brake Temp 3
		brakeTemps[3] = readThermocouples(GPIOD,GPIO_PIN_11);//Brake Temp 4

		for(int i = 0; i < NUM_BRAKE_TEMP_SENSORS;i++){
		       time = get_time();

		//                /* TODO: correlate the index "i" with the correct physical ADC channel
		//                 since the index may not align with the correct channel in the future */
		        int written = sprintf(buffer_pos, "[%s] Thermocouple #%d Temp %.5f°C\r\n", time, i, brakeTemps[i]);
		        buffer_pos += written;

		        HAL_USART_Transmit(&husart2, (uint8_t *) concatenatedDistanceMessages, buffer_pos-concatenatedDistanceMessages, 1000);
		        /* Logging Ends */
		        buffer_pos = concatenatedDistanceMessages;
		}


        uint8_t brakeTempCanData[8];
        convertDoubleToCAN(brakeTemps,brakeTempCanData);
        uint8_t sendStatus = sendCan(&hcan2,brakeTempCanData,8,BRAKE_TEMP_CAN_ID,CAN_RTR_DATA,0);
        if(sendStatus != 0x0)
        {
            logMessage("Brake Temp CAN send failed\r\n",true);
        }
		osDelay(pdMS_TO_TICKS(BRAKETEMP_DELAY_MS));
	}
	osThreadYield();
}

